### ISSUE TITLE
Erros apresentado no projeto 

### ISSUE THREAD

**Issue by cbotelho80** [circlecodesolution/vscode-ext-flutter-color-viewer#22]
allcollorShow.ts: 
"Não é possível localizar o módulo 'vscode' ou suas declarações de tipo correspondentes.ts(2307)"

extension.ts:
"Não é possível localizar o módulo 'vscode' ou suas declarações de tipo correspondentes.ts(2307)"

FlutterColorShow.ts:
"Não é possível localizar o módulo 'vscode' ou suas declarações de tipo correspondentes.ts(2307)"

**Comment by nileshchavan0611** [comment]
Hi @cbotelho80 ,
Sorry for late reply, can you please provide more details when you are getting this error

And also can you provide your environment details

**Comment by neodisk17** [comment]
Closing this issue as no further discussion is going-on, feel free to open it again.
