### ISSUE TITLE
Support for colors in manifest.json as well

### ISSUE THREAD

**Issue by MewX** [circlecodesolution/vscode-ext-flutter-color-viewer#6]
There are colors defined like this:

```
    "background_color": "#0175C2",
    "theme_color": "#0175C2"
```

**Comment by circlecodesolution** [comment]
Thank you so much for your feedback. we have added this feature on our latest version 0.1.0.

**Comment by Marcelovv2** [comment]
Hi, 
Does this require configuration? is not working for me out of the box.
![image](https://user-images.githubusercontent.com/19412353/99099978-ce3c8580-25a0-11eb-88fc-2fe560edd07c.png)

**Comment by MewX** [comment]
Colors in json never worked for me though.

**Comment by nileshchavan0611** [comment]
Hi @MewX & @Marcelovv2 ,
Thank you for your reply
I have found out that, I have missed the activation event in the plugin, due to which the plugin was not working.  I have fixed it and updated the plugin.

Please let me know if it's still not working for you

**Comment by Marcelovv2** [comment]
@nileshchavan0611 
Awesome! It's working now.
